/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.cput.billinterface;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;

/**
 *
 * @author Charles
 */
public class InterfaceBill extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceBill
     */
    private double tempDrink;
    private double tempMeal;
    private double tempDessert;
    private double tempAlcohol;
    private double totalPrice;
    private double totalDrinkPrice = 0.0;
    private double totalMealPrice = 0.0;
    private double totalDessertPrice = 0.0;
    private double totalAlcoholPrice = 0.0;

    public InterfaceBill() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txtOrderNumber.setEditable(false);
        txtMealBill.setEditable(false);
        txtTotalCost.setEditable(false);
        buttonActions(btnSubmitOrder);
        buttonActionsApprovalBtn(btnAccept, Color.GREEN);
        buttonActionsApprovalBtn(btnCancel, Color.RED);
        buttonActionsApprovalBtn();
        txtTip.setText("0");
        randomizer();

        txtQtyDrink.setText("0");
        txtQtyMeal.setText("0");
        txtQtyAlcohol.setText("0");
        txtQtyDessert.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
     public void txtValidation() {
        if (txtOrderNumber.getText().isEmpty() || txtMealBill.getText().isEmpty() || txtTotalCost.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Order Information Required");
        } else {
            Payment pymt = new Payment();
            pymt.startUserGUI();
            this.dispose();
        }
    }
    public static void startGUI() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceBill().setVisible(true);
            }
        });
    }

    public void randomizer() {
        int max = 20;
        int min = 1;
        int rand = (int) (Math.random() * (max - min + 1) + min);
        txtOrderNumber.setText(String.valueOf(rand));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblDrinks = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMealImage = new javax.swing.JLabel();
        lblDrinkImage1 = new javax.swing.JLabel();
        cbDrink = new javax.swing.JComboBox<>();
        cbMeal = new javax.swing.JComboBox<>();
        txtQtyDrink = new javax.swing.JTextField();
        lblQtyDrink = new javax.swing.JLabel();
        txtQtyMeal = new javax.swing.JTextField();
        lblQtyMeal = new javax.swing.JLabel();
        cbDessert = new javax.swing.JComboBox<>();
        lblDessertImage = new javax.swing.JLabel();
        lblDessert = new javax.swing.JLabel();
        lblQtyDessert = new javax.swing.JLabel();
        txtQtyDessert = new javax.swing.JTextField();
        lblAlcoholImage = new javax.swing.JLabel();
        lblAlcohol = new javax.swing.JLabel();
        cbAlcohol = new javax.swing.JComboBox<>();
        txtQtyAlcohol = new javax.swing.JTextField();
        lblQtyAlcohol = new javax.swing.JLabel();
        btnSubmitOrder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblOrderNumber = new javax.swing.JLabel();
        txtOrderNumber = new javax.swing.JTextField();
        lblTableNumber = new javax.swing.JLabel();
        txtTableNumber = new javax.swing.JTextField();
        lblMealBill = new javax.swing.JLabel();
        txtMealBill = new javax.swing.JTextField();
        lblTip = new javax.swing.JLabel();
        txtTip = new javax.swing.JTextField();
        lblTotalCost = new javax.swing.JLabel();
        txtTotalCost = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        lblDrinks.setBackground(new java.awt.Color(0, 0, 0));
        lblDrinks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDrinks.setForeground(new java.awt.Color(0, 0, 0));
        lblDrinks.setText("Beverages");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Meals");

        lblMealImage.setForeground(new java.awt.Color(0, 0, 0));
        lblMealImage.setIcon(new javax.swing.ImageIcon("Images\\hamburger.png")); // NOI18N

        lblDrinkImage1.setForeground(new java.awt.Color(0, 0, 0));
        lblDrinkImage1.setIcon(new javax.swing.ImageIcon("Images\\drink-icon.png")); // NOI18N

        cbDrink.setBackground(new java.awt.Color(153, 153, 153));
        cbDrink.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbDrink.setForeground(new java.awt.Color(255, 255, 255));
        cbDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Beverage", "Coke 1.5L : R19.00", "Jive 2L : R11.00", "Sprite 500ml : R10.00", "Ice Tea : R28.90", "Sparkling Water : R24.90" }));
        cbDrink.setBorder(null);
        cbDrink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDrinkActionPerformed(evt);
            }
        });

        cbMeal.setBackground(new java.awt.Color(153, 153, 153));
        cbMeal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbMeal.setForeground(new java.awt.Color(255, 255, 255));
        cbMeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Meal", "Cheese Burger: R89.00", "Pork Ribs : R159.90", "Lamp Chops : R239.90", "Veggie Burger : R89.90", "Chicken Salad : R59.90   " }));
        cbMeal.setBorder(null);
        cbMeal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMealActionPerformed(evt);
            }
        });

        txtQtyDrink.setBackground(new java.awt.Color(153, 153, 153));
        txtQtyDrink.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQtyDrink.setForeground(new java.awt.Color(255, 255, 255));
        txtQtyDrink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblQtyDrink.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQtyDrink.setForeground(new java.awt.Color(0, 0, 0));
        lblQtyDrink.setText("Qty");
        lblQtyDrink.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtQtyMeal.setBackground(new java.awt.Color(153, 153, 153));
        txtQtyMeal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQtyMeal.setForeground(new java.awt.Color(255, 255, 255));
        txtQtyMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblQtyMeal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQtyMeal.setForeground(new java.awt.Color(0, 0, 0));
        lblQtyMeal.setText("Qty");
        lblQtyMeal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbDessert.setBackground(new java.awt.Color(153, 153, 153));
        cbDessert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbDessert.setForeground(new java.awt.Color(255, 255, 255));
        cbDessert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Dessert", "Classic Waffle : R46.90", "Bar-One Waffle : R52.90", "Malva Pudding : R56.90", "Chocolate Brownie: R62.90", "Chocolate Cake : R59.20 " }));
        cbDessert.setBorder(null);
        cbDessert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDessertActionPerformed(evt);
            }
        });

        lblDessertImage.setForeground(new java.awt.Color(0, 0, 0));
        lblDessertImage.setIcon(new javax.swing.ImageIcon("Images\\dessert-icon.png")); // NOI18N

        lblDessert.setBackground(new java.awt.Color(0, 0, 0));
        lblDessert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDessert.setForeground(new java.awt.Color(0, 0, 0));
        lblDessert.setText("Dessert");

        lblQtyDessert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQtyDessert.setForeground(new java.awt.Color(0, 0, 0));
        lblQtyDessert.setText("Qty");
        lblQtyDessert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtQtyDessert.setBackground(new java.awt.Color(153, 153, 153));
        txtQtyDessert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQtyDessert.setForeground(new java.awt.Color(255, 255, 255));
        txtQtyDessert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblAlcoholImage.setForeground(new java.awt.Color(0, 0, 0));
        lblAlcoholImage.setIcon(new javax.swing.ImageIcon("Images\\alcohol-icon.png")); // NOI18N

        lblAlcohol.setBackground(new java.awt.Color(0, 0, 0));
        lblAlcohol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAlcohol.setForeground(new java.awt.Color(0, 0, 0));
        lblAlcohol.setText("Alcohol");

        cbAlcohol.setBackground(new java.awt.Color(153, 153, 153));
        cbAlcohol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbAlcohol.setForeground(new java.awt.Color(255, 255, 255));
        cbAlcohol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Alcohol", "Amstel : R28.90", "Heineken : R33.90", "Windhoek : R35.90", "Castle Lite : R30.90", "Nederburg Rosé : R38.90" }));
        cbAlcohol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbAlcohol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlcoholActionPerformed(evt);
            }
        });

        txtQtyAlcohol.setBackground(new java.awt.Color(153, 153, 153));
        txtQtyAlcohol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQtyAlcohol.setForeground(new java.awt.Color(255, 255, 255));
        txtQtyAlcohol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblQtyAlcohol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQtyAlcohol.setForeground(new java.awt.Color(0, 0, 0));
        lblQtyAlcohol.setText("Qty");
        lblQtyAlcohol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSubmitOrder.setBackground(new java.awt.Color(153, 153, 153));
        btnSubmitOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmitOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitOrder.setText("Submit Order");
        btnSubmitOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnSubmitOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblDessertImage)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblQtyDessert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQtyDessert, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblQtyDrink, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                            .addComponent(txtQtyDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addComponent(cbDessert, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblDrinkImage1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(lblDrinks)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblDessert)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblAlcohol)
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAlcoholImage, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblQtyAlcohol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQtyAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblMealImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblQtyMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQtyMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(btnSubmitOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDrinks, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQtyDrink)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtyDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQtyMeal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtyMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMealImage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDrinkImage1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDessert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblQtyDessert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtyDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDessertImage, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAlcohol)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblQtyAlcohol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtyAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAlcoholImage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmitOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        BackgroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 76, 510, 431));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        lblOrderNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOrderNumber.setForeground(new java.awt.Color(0, 0, 0));
        lblOrderNumber.setText("Order Number");

        txtOrderNumber.setBackground(new java.awt.Color(153, 153, 153));
        txtOrderNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtOrderNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtOrderNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblTableNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTableNumber.setForeground(new java.awt.Color(0, 0, 0));
        lblTableNumber.setText("Table Number");

        txtTableNumber.setBackground(new java.awt.Color(153, 153, 153));
        txtTableNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTableNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtTableNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblMealBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMealBill.setForeground(new java.awt.Color(0, 0, 0));
        lblMealBill.setText("Meal Bill");

        txtMealBill.setBackground(new java.awt.Color(153, 153, 153));
        txtMealBill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMealBill.setForeground(new java.awt.Color(255, 255, 255));
        txtMealBill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblTip.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTip.setForeground(new java.awt.Color(0, 0, 0));
        lblTip.setText("Gratitude");

        txtTip.setBackground(new java.awt.Color(153, 153, 153));
        txtTip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTip.setForeground(new java.awt.Color(255, 255, 255));
        txtTip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblTotalCost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalCost.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalCost.setText("Total Cost");

        txtTotalCost.setBackground(new java.awt.Color(153, 153, 153));
        txtTotalCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTotalCost.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        btnCancel.setBackground(new java.awt.Color(255, 0, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel Payment");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAccept.setBackground(new java.awt.Color(51, 255, 0));
        btnAccept.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAccept.setForeground(new java.awt.Color(255, 255, 255));
        btnAccept.setText("Approve Payment");
        btnAccept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnAccept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccept, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTip)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTableNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMealBill, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTip, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTotalCost)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTableNumber)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMealBill)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblOrderNumber)
                        .addGap(19, 19, 19)))
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblOrderNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTableNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTableNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMealBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMealBill, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTip, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalCost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        BackgroundPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 76, -1, 430));

        lblIcon.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIcon.setForeground(new java.awt.Color(0, 0, 0));
        lblIcon.setIcon(new javax.swing.ImageIcon("D:\\ApplicationWork\\Java\\practice task\\BillInterface\\BillInterface\\Images\\pizza-icon.png")); // NOI18N
        BackgroundPanel.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, 58));

        lblHome.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblHome.setForeground(new java.awt.Color(0, 0, 0));
        lblHome.setText("RESTAURANT APP");
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackgroundPanel.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 262, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\ApplicationWork\\Java\\practice task\\BillInterface\\BillInterface\\Images\\background.jpg")); // NOI18N
        BackgroundPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BackgroundPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //--------------------------------------------------------------------------Cancel Order btn 
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        popup = new JFrame();

        JOptionPane.showConfirmDialog(popup, "Order has been cancelled", "Order cancelled", JOptionPane.CLOSED_OPTION);

        
        txtMealBill.setText("");
      
        txtTotalCost.setText("");
        cbDrink.setSelectedIndex(0);
        cbMeal.setSelectedIndex(0);
        cbDessert.setSelectedIndex(0);
        cbAlcohol.setSelectedIndex(0);
        txtQtyDrink.setText("0");
        txtQtyMeal.setText("0");
        txtQtyDessert.setText("0");
        txtQtyAlcohol.setText("0");
    }//GEN-LAST:event_btnCancelActionPerformed
    //--------------------------------------------------------------------------Approve Order btn 
    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your approve order handling code here:
        txtValidation();
    }//GEN-LAST:event_btnAcceptActionPerformed
    //--------------------------------------------------------------------------cb Drinks event
    private void cbDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDrinkActionPerformed
        // TODO add your handling code here:
        //action performed multiplied by quantity
        String selectedItem = cbDrink.getSelectedItem().toString();
        if (selectedItem.equals("Coke 1.5L : R19.00")) {
            tempDrink = 19.00;

        }
        if (selectedItem.equals("Jive 2L : R11.00")) {
            tempDrink = 11.00;

        }
        if (selectedItem.equals("Sprite 500ml : R10.00")) {
            tempDrink = 10.00;

        }
        if (selectedItem.equals("Ice Tea : R28.90")) {
            tempDrink = 28.90;

        }
        if (selectedItem.equals("Sparkling Water : R24.90")) {
            tempDrink = 24.90;

        }

    }//GEN-LAST:event_cbDrinkActionPerformed
    //--------------------------------------------------------------------------Submit button
    private void btnSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitOrderActionPerformed
        // TODO add your handling code here:
        calculateTotalCosts();
        System.out.println("R" + totalPrice);
    }//GEN-LAST:event_btnSubmitOrderActionPerformed
    private void calculateTotalCosts() {
        //drinks
        double price = Double.parseDouble(txtQtyDrink.getText());
        totalDrinkPrice = tempDrink * price;
        System.out.println(totalDrinkPrice);

        //meals
        double mealPrice = Double.parseDouble(txtQtyMeal.getText());
        totalMealPrice = tempMeal * mealPrice;
        System.out.println(totalMealPrice);

        //Dessert
        double dessertPrice = Double.parseDouble(txtQtyDessert.getText());
        totalDessertPrice = tempDessert * dessertPrice;
        System.out.println(totalDessertPrice);

        //Alcohol
        double alcoholPrice = Double.parseDouble(txtQtyAlcohol.getText());
        totalAlcoholPrice = tempAlcohol * alcoholPrice;
        System.out.println(totalAlcoholPrice);

        totalPrice = totalDrinkPrice + totalMealPrice + totalDessertPrice + totalAlcoholPrice;

        txtMealBill.setText("R" + String.valueOf(totalPrice));

        double sum = totalPrice + Double.parseDouble(txtTip.getText());
        txtTotalCost.setText("R" + String.valueOf(sum));

    }

    //--------------------------------------------------------------------------cb Meal event
    private void cbMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMealActionPerformed
        // TODO add your handling code here:
        String selectedItem = cbMeal.getSelectedItem().toString();
        if (selectedItem.equals("Cheese Burger: R89.00")) {
            tempMeal = 89.00;

        }
        if (selectedItem.equals("Pork Ribs : R159.90")) {
            tempMeal = 159.90;

        }
        if (selectedItem.equals("Lamp Chops : R239.90")) {
            tempMeal = 239.90;

        }
        if (selectedItem.equals("Veggie Burger : R89.90")) {
            tempMeal = 89.90;

        }
        if (selectedItem.equals("Chicken Salad : R59.90")) {
            tempMeal = 59.90;

        }

    }//GEN-LAST:event_cbMealActionPerformed
    //--------------------------------------------------------------------------cb Dessert event
    private void cbDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDessertActionPerformed
        // TODO add your handling code here:

        String selectedItem = cbDessert.getSelectedItem().toString();
        if (selectedItem.equals("Classic Waffle : R46.90")) {
            tempDessert = 46.90;

        }
        if (selectedItem.equals("Bar-One Waffle : R52.90")) {
            tempDessert = 52.90;

        }
        if (selectedItem.equals("Malva Pudding : R56.90")) {
            tempDessert = 56.90;

        }
        if (selectedItem.equals("Chocolate Brownie: R62.90")) {
            tempDessert = 62.90;

        }
        if (selectedItem.equals("Chocolate Cake : R59.20")) {
            tempDessert = 59.20;

        }
    }//GEN-LAST:event_cbDessertActionPerformed
    //--------------------------------------------------------------------------cb Alcohol event
    private void cbAlcoholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlcoholActionPerformed
        // TODO add your handling code here:

        String selectedItem = cbAlcohol.getSelectedItem().toString();
        if (selectedItem.equals("Amstel : R28.90")) {
            tempAlcohol = 28.90;

        }
        if (selectedItem.equals("Heineken : R33.90")) {
            tempAlcohol = 33.90;

        }
        if (selectedItem.equals("Windhoek : R35.90")) {
            tempAlcohol = 35.90;

        }
        if (selectedItem.equals("Castle Lite : R30.90")) {
            tempAlcohol = 30.90;

        }
        if (selectedItem.equals("Nederburg Rosé : R38.90")) {
            tempAlcohol = 38.90;

        }

    }//GEN-LAST:event_cbAlcoholActionPerformed
    private void buttonActions(final JButton button) {
        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(Color.WHITE);
                button.setForeground(Color.GRAY);
                button.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 3));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(Color.GRAY);
                button.setForeground(Color.WHITE);
                button.setBorder(BorderFactory.createLineBorder(Color.WHITE, 3));
            }
        });
    }

    private void buttonActionsApprovalBtn(final JButton button, Color colors) {
        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(Color.WHITE);
                button.setForeground(Color.GRAY);
                button.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 3));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(colors);
                button.setForeground(Color.WHITE);
                button.setBorder(BorderFactory.createLineBorder(Color.WHITE, 3));
            }
        });
    }

    public void buttonActionsApprovalBtn() {
        lblHome.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                HomeScreen opn = new HomeScreen();
                opn.startUI();
                dispose();
            }

        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmitOrder;
    private javax.swing.JComboBox<String> cbAlcohol;
    private javax.swing.JComboBox<String> cbDessert;
    private javax.swing.JComboBox<String> cbDrink;
    private javax.swing.JComboBox<String> cbMeal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAlcohol;
    private javax.swing.JLabel lblAlcoholImage;
    private javax.swing.JLabel lblDessert;
    private javax.swing.JLabel lblDessertImage;
    private javax.swing.JLabel lblDrinkImage1;
    private javax.swing.JLabel lblDrinks;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMealBill;
    private javax.swing.JLabel lblMealImage;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblQtyAlcohol;
    private javax.swing.JLabel lblQtyDessert;
    private javax.swing.JLabel lblQtyDrink;
    private javax.swing.JLabel lblQtyMeal;
    private javax.swing.JLabel lblTableNumber;
    private javax.swing.JLabel lblTip;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JTextField txtMealBill;
    private javax.swing.JTextField txtOrderNumber;
    private javax.swing.JTextField txtQtyAlcohol;
    private javax.swing.JTextField txtQtyDessert;
    private javax.swing.JTextField txtQtyDrink;
    private javax.swing.JTextField txtQtyMeal;
    private javax.swing.JTextField txtTableNumber;
    private javax.swing.JTextField txtTip;
    private javax.swing.JTextField txtTotalCost;
    private javax.swing.JFrame popup;
    // End of variables declaration//GEN-END:variables
}
