/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.cput.billinterface;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author FARAI SKOOL
 */
public class Payment extends javax.swing.JFrame {

    int cardPin = 1234;
    String email="akutsuki@gmail.com";

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        lblValidation2.setVisible(false);
        lblValidation1.setVisible(false);
        btnClearReset.setEnabled(false);
        btnPay.setEnabled(false);
        dateComb.setEnabled(false);
        cboDate();
        buttonActions(btnPay);
        buttonActions(btnClearReset);
    }

    public void cboDate() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        dateComb.addItem(+year + "-" + (month + 1) + "-" + day);
        dateComb.addItem(+year + "-" + (month + 1) + "-" + (day + 1));

    }

    public void startUserGUI() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    public void CardNumValidation() {
        if (txtFdCardNum1.getText().isEmpty()) {

            lblValidation1.setVisible(true);
        } else {
            lblValidation1.setVisible(false);
        }
    }

    public void CardNumValidationLength() {
        if (txtFdCardNum1.getText().length() != 16) {
            JOptionPane.showMessageDialog(null, "Card Number INCOMPLETE");
        }
    }

    public void ccvValidation() {
        if (txtFdCardPin.getText().isEmpty()) {

            lblValidation2.setVisible(true);
        } else {
            lblValidation2.setVisible(false);
        }

    }

    public void onlinePayment(){
    
    String input;
            String verifyPin;
            input = JOptionPane.showInputDialog("Enter Email for Receits ");
            verifyPin = input;

            if (email.equals(verifyPin)) {
                JOptionPane.showMessageDialog(null, "Email valid");
                JOptionPane.showMessageDialog(null, "Payment SuccessFull");
                HomeScreen opn = new HomeScreen();
                opn.startUI();
                dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Pin Incorrect");
            }
    
    }
    public void CardPayment() {

        if (jRadioBtnPP.isSelected()) {

            String input;
            int verifyPin;
            input = JOptionPane.showInputDialog("Enter Pin ");
            verifyPin = Integer.parseInt(input);

            if (cardPin == verifyPin) {
                JOptionPane.showMessageDialog(null, "Pin Ok");
                JOptionPane.showMessageDialog(null, "Payment SuccessFull");
                HomeScreen opn = new HomeScreen();
                opn.startUI();
                dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Pin Incorrect");
            }

        }

    }
   private void buttonActions(final JButton button) {
        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(Color.WHITE);
                button.setForeground(Color.GRAY);
                button.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 3));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground(Color.GRAY);
                button.setForeground(Color.WHITE);
                button.setBorder(BorderFactory.createLineBorder(Color.WHITE, 3));
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioBtnPP = new javax.swing.JRadioButton();
        jRadioBtnCard = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtFdCardNum1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFdCardPin = new javax.swing.JTextField();
        lblValidation2 = new javax.swing.JLabel();
        dateComb = new javax.swing.JComboBox<>();
        lblValidation1 = new javax.swing.JLabel();
        btnClearReset = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblPP = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblIcon1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioBtnPP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioBtnPP.setForeground(new java.awt.Color(0, 0, 0));
        jRadioBtnPP.setText("Card");
        jRadioBtnPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtnPPActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioBtnPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 57, -1));

        jRadioBtnCard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioBtnCard.setForeground(new java.awt.Color(0, 0, 0));
        jRadioBtnCard.setText("Online");
        jRadioBtnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtnCardActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioBtnCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Card Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 85, -1));

        txtFdCardNum1.setBackground(new java.awt.Color(153, 153, 153));
        txtFdCardNum1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFdCardNum1.setForeground(new java.awt.Color(255, 255, 255));
        txtFdCardNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtFdCardNum1.setEnabled(false);
        txtFdCardNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFdCardNum1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtFdCardNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 182, 265, 30));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CCV Code");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 85, -1));

        txtFdCardPin.setBackground(new java.awt.Color(153, 153, 153));
        txtFdCardPin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFdCardPin.setForeground(new java.awt.Color(255, 255, 255));
        txtFdCardPin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtFdCardPin.setEnabled(false);
        jPanel1.add(txtFdCardPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 282, 100, 30));

        lblValidation2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValidation2.setForeground(new java.awt.Color(204, 0, 0));
        lblValidation2.setText("required*");
        lblValidation2.setEnabled(false);
        jPanel1.add(lblValidation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 111, 23));

        dateComb.setBackground(new java.awt.Color(153, 153, 153));
        dateComb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateComb.setForeground(new java.awt.Color(255, 255, 255));
        dateComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yy/mm" }));
        jPanel1.add(dateComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 100, 30));

        lblValidation1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValidation1.setForeground(new java.awt.Color(204, 0, 0));
        lblValidation1.setText("required*");
        lblValidation1.setEnabled(false);
        jPanel1.add(lblValidation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 70, 43));

        btnClearReset.setBackground(new java.awt.Color(153, 153, 153));
        btnClearReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearReset.setForeground(new java.awt.Color(255, 255, 255));
        btnClearReset.setText("Verify");
        btnClearReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnClearReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnClearReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 110, 30));

        btnReset.setText("jButton1");
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1168, 290, 89, 31));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 330, 220));
        jPanel1.add(lblPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 124, 111, 23));

        btnPay.setBackground(new java.awt.Color(153, 153, 153));
        btnPay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Pay");
        btnPay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 110, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("Images\\card.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 330, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 740, 380));

        lblIcon.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, 58));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("RESTUARANT APP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 262, -1));

        lblIcon1.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIcon1.setForeground(new java.awt.Color(0, 0, 0));
        lblIcon1.setIcon(new javax.swing.ImageIcon("Images\\pizza-icon.png")); // NOI18N
        getContentPane().add(lblIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, 58));

        jLabel7.setIcon(new javax.swing.ImageIcon("Images\\background.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioBtnCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtnCardActionPerformed
        // TODO add your handling code here:
        if (jRadioBtnCard.isContentAreaFilled()) {
            txtFdCardNum1.setEnabled(true);
            txtFdCardPin.setEnabled(true);
            btnClearReset.setEnabled(true);
            btnPay.setEnabled(true);
            dateComb.setEnabled(true);

        }
        if (!jRadioBtnCard.isSelected()) {
            txtFdCardNum1.setEnabled(false);
            txtFdCardPin.setEnabled(false);
            btnClearReset.setEnabled(false);
            btnPay.setEnabled(false);
            dateComb.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioBtnCardActionPerformed

    private void btnClearResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearResetActionPerformed
        // TODO add your handling code here:
        CardNumValidation();
        CardNumValidationLength();
        ccvValidation();
        
        //CardNumValidationLength();
    }//GEN-LAST:event_btnClearResetActionPerformed

    private void txtFdCardNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFdCardNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFdCardNum1ActionPerformed

    private void jRadioBtnPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtnPPActionPerformed
        // TODO add your handling code here:
        CardPayment();

    }//GEN-LAST:event_jRadioBtnPPActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        if(txtFdCardPin.getText().isEmpty()||txtFdCardPin.getText().isEmpty()){
        
             JOptionPane.showMessageDialog(null, "Please fill card details");
        } else
        onlinePayment();
        txtFdCardNum1.setText("");
        txtFdCardPin.setText("");
    }//GEN-LAST:event_btnPayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearReset;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dateComb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioBtnCard;
    private javax.swing.JRadioButton jRadioBtnPP;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblPP;
    private javax.swing.JLabel lblValidation1;
    private javax.swing.JLabel lblValidation2;
    private javax.swing.JTextField txtFdCardNum1;
    private javax.swing.JTextField txtFdCardPin;
    // End of variables declaration//GEN-END:variables
}
